- name: 🏔·
  description: Above tree line
  color: ffffff
- name: 🌲·
  description: Below tree line
  color: ffffff

- name: 'cooldown: 5.10 - 5.21'
  description: ❄️
  color: afc6f2
- name: 'cooldown: 06.21 - 06.25'
  description: ❄️
  color: afc6f2
- name: 'cooldown: 07.26 - 07.30'
  description: ❄️
  color: afc6f2
- name: 'cooldown: 08.30 - 09.03'
  description: ❄️
  color: afc6f2

- name: 'cycle: 3.29 - 5.7'
  description: 🌧
  color: d08f45
- name: 'cycle: 5.24 - 6.18'
  description: ☀️
  color: d93f0b
- name: 'cycle: 06.28 - 07.23'
  description: ⛅️
  color: 7ebe3e
- name: 'cycle: 08.02 - 08.27'
  description: 🌥
  color: 5e614b

- name: BE
  description: Backend work
  color: 4395f2
- name: bug
  description: Something isn't working
  color: e9282c
- name: chore
  description: A non issue related ticket
  color: 3d3937
- name: FE
  description: Frontend work
  color: f9980d
- name: feature
  description: The fun stuff
  color: c5def5
