name-template: v$NEXT_PATCH_VERSION 🌈
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    labels:
      - feature
      - big batch
      - small batch
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bug
  - title: 🧰 Maintenance
    labels:
      - chore
  - title: 📦️ Dependencies
    labels:
      - dependencies
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
