name: Sync labels
on:
  push:
    branches:
      - main
    # paths:
    # - .github/labels.yml
    # - .github/workflows/gh-labels.yml
jobs:
  label_sync:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - vangst/smokey
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: ${{ matrix.repo }}
          token: ${{ secrets.VANGST_ROBOT_TOKEN }}
          # prune: false
