name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
      - name: Sync to vangst/smokey
        env:
          VANGST_ROBOT_TOKEN: ${{ secrets.VANGST_ROBOT_TOKEN }}
        run: |
          curl -X POST -H 'Content-type: application/json' -H 'Accept: application/vnd.github.everest-preview+json' -H 'Authorization: token $(VANGST_ROBOT_TOKEN)' --data '{"event_type": "labeler"}' https://api.github.com/repos/vangst/smokey/dispatches
