name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          VANGST_ROBOT_TOKEN: ${{ secrets.VANGST_ROBOT_TOKEN }}
        with:
          manifest: .github/labels.yml
          repository: |
            vangst/smokey
          token: ${{ secrets.VANGST_ROBOT_TOKEN }}
